# Generated by Django 3.1.1 on 2020-09-18 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kazananlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winersmodel',
            name='name',
            field=models.CharField(max_length=15, verbose_name='İsim Ekleyin'),
        ),
    ]
