# Generated by Django 3.1.1 on 2020-09-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('pragraf', models.CharField(max_length=300, verbose_name='pragraf')),
                ('pragrafiki', models.CharField(max_length=300, verbose_name='pragrafiki')),
                ('pragrafüç', models.CharField(max_length=300, verbose_name='pragrafüç')),
                ('pragrafdört', models.CharField(max_length=300, verbose_name='pragrafdört')),
                ('pragrafbeş', models.CharField(max_length=300, verbose_name='pragrafbeş')),
                ('titlealtı', models.CharField(max_length=300, verbose_name='titlealtı')),
                ('totalyedi', models.CharField(max_length=300, verbose_name='totalyedi')),
            ],
            options={
                'verbose_name': 'Biz Kimiz',
                'verbose_name_plural': 'Biz Kimiz',
                'ordering': ['title'],
            },
        ),
    ]
