# Generated by Django 3.1.1 on 2020-09-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkımızda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='pragrafbeş',
            field=models.CharField(blank=True, max_length=300, verbose_name='pragrafbeş'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='titlealtı',
            field=models.CharField(blank=True, max_length=300, verbose_name='titlealtı'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='totalyedi',
            field=models.CharField(blank=True, max_length=300, verbose_name='totalyedi'),
        ),
    ]
