# Generated by Django 3.1.1 on 2020-09-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hakkımızda', '0002_auto_20200918_0057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='titlealtı',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='totalyedi',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='pragrafaltı',
            field=models.CharField(blank=True, max_length=300, verbose_name='pragrafaltı'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='pragrafyedi',
            field=models.CharField(blank=True, max_length=300, verbose_name='pragrafyedi'),
        ),
    ]
