# Generated by Django 3.1.1 on 2020-09-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Başlık Ekleyin')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin')),
                ('acıklama', models.CharField(max_length=100, verbose_name='Aççıklama Ekleyin')),
                ('fiyat', models.CharField(max_length=3, verbose_name='Fiyat Ekleyin')),
                ('bölüm', models.CharField(choices=[('kahveler', 'KAHVELER'), ('latteler', 'LATTELER'), ('sıcak çikolata', 'SICAK ÇİKOLATA'), ('çaylar', 'ÇAYLAR')], default='çaylar', max_length=30)),
            ],
            options={
                'verbose_name': 'Menü',
                'verbose_name_plural': 'Menü',
                'ordering': ['title'],
            },
        ),
    ]
