# Generated by Django 3.1.1 on 2020-09-18 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menumodel',
            old_name='acıklama',
            new_name='aciklama',
        ),
    ]
