# Generated by Django 3.1.1 on 2020-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200918_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='fiyat',
            field=models.CharField(max_length=10, verbose_name='Fiyat Ekleyin'),
        ),
    ]
