# Generated by Django 3.1.1 on 2020-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200919_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Başlık Ekleyin'),
        ),
    ]
