# Generated by Django 3.1.1 on 2020-09-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0003_auto_20200917_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=50, verbose_name='Başlık')),
            ],
            options={
                'ordering': ['total'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
