# Generated by Django 3.1.1 on 2020-09-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_auto_20200917_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalmodel',
            options={'ordering': ['total'], 'verbose_name': 'My image', 'verbose_name_plural': 'My images'},
        ),
    ]
