# Generated by Django 3.1.1 on 2020-09-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_auto_20200918_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CekilisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('kazandı', 'Kazandı'), ('beklemede', 'Beklemede')], default='beklemede', max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=25)),
                ('pill', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Çekiliş Katılımları',
                'verbose_name_plural': 'Çekiliş Katılımları',
                'ordering': ['status'],
            },
        ),
    ]
