# Generated by Django 3.1.1 on 2020-09-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0008_cekilismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kahvesayisimodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Başlık Ekleyin')),
                ('subtitle', models.CharField(max_length=30, verbose_name='Alt Başlık Ekleyin')),
                ('pragraf', models.CharField(max_length=30, verbose_name='Açıklama Ekleyin')),
                ('slogan', models.CharField(max_length=30, verbose_name='Slogan Ekleyin')),
            ],
            options={
                'verbose_name': 'Kahve Sayısı Açıklaması',
                'verbose_name_plural': 'Kahve Sayısı Açıklaması',
                'ordering': ['title'],
            },
        ),
    ]
