# Generated by Django 3.1.1 on 2020-09-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0010_yardımsayisimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='slogan',
            field=models.CharField(blank=True, max_length=30, verbose_name='Slogan Ekleyin'),
        ),
    ]
