# Generated by Django 3.1.1 on 2020-09-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0011_auto_20200919_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kahveagacimodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Başlık Ekleyin')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Alt Başlık Ekleyin')),
                ('pragraf', models.CharField(blank=True, max_length=500, verbose_name='Açıklama Ekleyin')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='Slogan Ekleyin')),
            ],
            options={
                'verbose_name': 'Kahve Agacı Açıklaması',
                'verbose_name_plural': 'Kahve Agacı Açıklaması',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='kahvesayisimodel',
            name='pragraf',
            field=models.CharField(blank=True, max_length=500, verbose_name='Açıklama Ekleyin'),
        ),
        migrations.AlterField(
            model_name='kahvesayisimodel',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, verbose_name='Slogan Ekleyin'),
        ),
        migrations.AlterField(
            model_name='kahvesayisimodel',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name='Alt Başlık Ekleyin'),
        ),
        migrations.AlterField(
            model_name='kahvesayisimodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Başlık Ekleyin'),
        ),
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='pragraf',
            field=models.CharField(blank=True, max_length=500, verbose_name='Açıklama Ekleyin'),
        ),
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, verbose_name='Slogan Ekleyin'),
        ),
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='subtitle',
            field=models.CharField(max_length=500, verbose_name='Alt Başlık Ekleyin'),
        ),
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Başlık Ekleyin'),
        ),
    ]
