# Generated by Django 3.1.1 on 2020-09-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0013_orangeboxmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Greeenboxmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=15, verbose_name='Birinci Satırı Ekleyin')),
                ('second', models.CharField(blank=True, max_length=15, verbose_name='İkinci Satırı Ekleyin')),
            ],
            options={
                'verbose_name': 'Yeşil kutu içeriği',
                'verbose_name_plural': 'Yeşil kutu içeriği',
                'ordering': ['first'],
            },
        ),
        migrations.CreateModel(
            name='Redboxmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=15, verbose_name='Birinci Satırı Ekleyin')),
                ('second', models.CharField(blank=True, max_length=15, verbose_name='İkinci Satırı Ekleyin')),
                ('third', models.CharField(blank=True, max_length=15, verbose_name='Üçüncü Satırı Ekleyin')),
                ('fourth', models.CharField(blank=True, max_length=15, verbose_name='Dördüncü Satır (Tl simgesi)')),
            ],
            options={
                'verbose_name': 'Kırmızı kutu içeriği',
                'verbose_name_plural': 'Kırmızı kutu içeriği',
                'ordering': ['first'],
            },
        ),
    ]
