# Generated by Django 3.1.1 on 2020-09-19 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0014_greeenboxmodel_redboxmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redboxmodel',
            name='fourth',
        ),
    ]
