# Generated by Django 3.1.1 on 2020-09-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0015_remove_redboxmodel_fourth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orangeboxmodel',
            options={'ordering': ['first'], 'verbose_name': 'Turuncu kutu içeriği', 'verbose_name_plural': 'Turuncu kutu içeriği'},
        ),
    ]
