# Generated by Django 3.1.1 on 2020-09-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0017_auto_20200923_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='kahveyardimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipname', models.CharField(blank=True, max_length=30, verbose_name='Yardım edenin ismi')),
                ('tipnote', models.CharField(max_length=500, null=True, verbose_name='Yardım edenin notu')),
            ],
            options={
                'verbose_name': 'Kahve Yardımı',
                'verbose_name_plural': 'Kahve Yardımları',
                'ordering': ['tipname'],
            },
        ),
        migrations.RemoveField(
            model_name='kahveagacimodel',
            name='tipname',
        ),
        migrations.RemoveField(
            model_name='kahveagacimodel',
            name='tipnote',
        ),
    ]
