# Generated by Django 3.1.1 on 2020-09-23 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0018_auto_20200923_0328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kahveyardimmodel',
            options={'ordering': ['tipname'], 'verbose_name': 'Kahve Alımları', 'verbose_name_plural': 'Kahve Alımları'},
        ),
    ]
