# Generated by Django 3.1.1 on 2020-09-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0019_auto_20200923_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotaltreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalcofee', models.CharField(max_length=50, verbose_name='Toplam ')),
            ],
            options={
                'verbose_name': 'Ağaçdaki Toplam  kahve Sayısı',
                'verbose_name_plural': 'Ağaçtaki Toplam  Kahve Sayısı',
                'ordering': ['totalcofee'],
            },
        ),
        migrations.AlterModelOptions(
            name='kahveyardimmodel',
            options={'ordering': ['tipname'], 'verbose_name': 'Kahve Alımları', 'verbose_name_plural': 'Kahve Alımı '},
        ),
        migrations.AlterModelOptions(
            name='totalmodel',
            options={'ordering': ['total'], 'verbose_name': 'Toplam satılan kahve Sayısı', 'verbose_name_plural': 'Toplam satılan Kahve Sayısı'},
        ),
    ]
