# Generated by Django 3.1.1 on 2020-09-23 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0021_auto_20200923_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cekilismodel',
            options={'ordering': ['status'], 'verbose_name': 'kırmızı kutu Çekiliş Katılımları', 'verbose_name_plural': 'Çekiliş Katılımları'},
        ),
    ]
