# Generated by Django 3.1.1 on 2020-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0025_auto_20200923_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totaltreemodel',
            options={'ordering': ['id'], 'verbose_name': 'Toplam Ağaçdaki  kahve Sayısı', 'verbose_name_plural': 'Toplam Ağaçtaki Kahve Sayısı'},
        ),
        migrations.RemoveField(
            model_name='totaltreemodel',
            name='totalcofee',
        ),
        migrations.AddField(
            model_name='totaltreemodel',
            name='totaldoctorcofee',
            field=models.CharField(max_length=50, null=True, verbose_name='Toplam kahve ( Sağlık personeli ) '),
        ),
        migrations.AddField(
            model_name='totaltreemodel',
            name='totalstudentcofee',
            field=models.CharField(max_length=50, null=True, verbose_name='Toplam kahve ( Öğrenci )'),
        ),
    ]
