# Generated by Django 3.1.1 on 2020-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0026_auto_20200927_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='kahvestudentyardimModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipname', models.CharField(blank=True, max_length=30, verbose_name='Yardım edenin ismi')),
                ('tipnote', models.CharField(max_length=500, null=True, verbose_name='Yardım edenin notu')),
            ],
            options={
                'verbose_name': 'Ağaca kahve ekleyenler',
                'verbose_name_plural': 'Ağaca kahve ekleyenler',
                'ordering': ['tipname'],
            },
        ),
        migrations.RenameModel(
            old_name='kahveyardimModel',
            new_name='kahvedoctoryardimModel',
        ),
        migrations.AlterModelOptions(
            name='kahvesayisimodel',
            options={'ordering': ['title'], 'verbose_name': 'Bugün satılan kahve Sayısı ', 'verbose_name_plural': 'Turuncu kutu satılan kahve Sayısı'},
        ),
    ]
