# Generated by Django 3.1.1 on 2020-09-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0027_auto_20200928_0027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kahvedoctoryardimmodel',
            options={'ordering': ['name'], 'verbose_name': 'Eklenen kahve (doktor)', 'verbose_name_plural': 'Eklenen kahveler (doktor)'},
        ),
        migrations.AlterModelOptions(
            name='kahvestudentyardimmodel',
            options={'ordering': ['name'], 'verbose_name': 'Eklenen kahve ( Öğrenci )', 'verbose_name_plural': 'Eklenen kahveler ( Öğrenci )'},
        ),
        migrations.RemoveField(
            model_name='kahvedoctoryardimmodel',
            name='tipname',
        ),
        migrations.RemoveField(
            model_name='kahvedoctoryardimmodel',
            name='tipnote',
        ),
        migrations.RemoveField(
            model_name='kahvestudentyardimmodel',
            name='tipname',
        ),
        migrations.RemoveField(
            model_name='kahvestudentyardimmodel',
            name='tipnote',
        ),
        migrations.AddField(
            model_name='kahvedoctoryardimmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kahvedoctoryardimmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresi'),
        ),
        migrations.AddField(
            model_name='kahvedoctoryardimmodel',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='kahvedoctoryardimmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası'),
        ),
        migrations.AddField(
            model_name='kahvestudentyardimmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kahvestudentyardimmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresi'),
        ),
        migrations.AddField(
            model_name='kahvestudentyardimmodel',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='İsim'),
        ),
        migrations.AddField(
            model_name='kahvestudentyardimmodel',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası'),
        ),
    ]
