# Generated by Django 3.1.1 on 2020-09-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0028_auto_20200928_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahvedoctoryardimmodel',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='İsim-Soyisim'),
        ),
        migrations.AlterField(
            model_name='kahvestudentyardimmodel',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='İsim-Soyisim'),
        ),
    ]
