# Generated by Django 3.1.1 on 2020-09-27 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0029_auto_20200928_0040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kahveagacimodel',
            options={'ordering': ['title'], 'verbose_name': 'Yeşil kutu Açıklamaları', 'verbose_name_plural': 'Yeşil kutu Açıklamaları'},
        ),
    ]
