# Generated by Django 3.1.1 on 2020-09-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0031_auto_20200928_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilregisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('teslimedildi', 'Teslim Edildi'), ('beklemede', 'Beklemede')], default='beklemede', max_length=15)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='İsim-Soyisim')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresi')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='Telefon Numarası')),
                ('pill', models.CharField(max_length=50, verbose_name='Fiş Numarası')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Fiş Kayıtı',
                'verbose_name_plural': 'Fiş Kayıtları',
                'ordering': ['created_date'],
            },
        ),
        migrations.DeleteModel(
            name='CekilisModel',
        ),
    ]
