# Generated by Django 3.1.1 on 2020-09-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0033_auto_20200928_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kahvesayisimodel',
            options={'ordering': ['title'], 'verbose_name': 'Şeffaf Kutu Açıklaması ', 'verbose_name_plural': 'Şeffaf Kutu Açıklaması'},
        ),
    ]
