# Generated by Django 3.1.1 on 2020-10-04 12:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0036_auto_20201004_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahvesayisimodel',
            name='pragraf',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama Ekleyin'),
        ),
    ]
