# Generated by Django 3.1.1 on 2020-10-04 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0037_auto_20201004_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='yardımsayisimodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin'),
        ),
        migrations.AlterField(
            model_name='yardımsayisimodel',
            name='pragraf',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama Ekleyin'),
        ),
    ]
