# Generated by Django 3.1.1 on 2020-10-04 14:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0039_auto_20201004_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='kahveagacimodel',
            name='imagedoctor',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Sağlık Çalışanı Ağacı Fotoğraf '),
        ),
        migrations.AlterField(
            model_name='kahveagacimodel',
            name='pragrafdoctor',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sağlık Çalışanı Ağacı Açıklama '),
        ),
    ]
