# Generated by Django 3.1.1 on 2020-10-04 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0040_auto_20201004_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kahvedoctoryardimmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='kahvestudentyardimmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pilregistermodel',
            name='email',
        ),
        migrations.AddField(
            model_name='kahvedoctoryardimmodel',
            name='note',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Not Ekleyin'),
        ),
        migrations.AddField(
            model_name='kahvestudentyardimmodel',
            name='note',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Not Ekleyin'),
        ),
    ]
