# Generated by Django 3.1.1 on 2020-10-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0041_auto_20201004_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahvedoctoryardimmodel',
            name='note',
            field=models.TextField(null=True, verbose_name='Not Ekleyin'),
        ),
    ]
