# Generated by Django 3.1.1 on 2020-10-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0042_auto_20201004_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kahvestudentyardimmodel',
            name='note',
            field=models.TextField(null=True, verbose_name='Not Ekleyin'),
        ),
    ]
