# Generated by Django 3.1.1 on 2020-10-04 16:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0043_auto_20201004_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pillregistercontextmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Başlık Ekleyin')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Alt Başlık Ekleyin')),
                ('pragraf', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama Ekleyin')),
                ('slogan', models.CharField(blank=True, max_length=500, verbose_name='Slogan Ekleyin')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf Ekleyin')),
            ],
            options={
                'verbose_name': 'Kırmızı Kutu Açıklaması ',
                'verbose_name_plural': 'Kırmızı Kutu Açıklaması',
                'ordering': ['title'],
            },
        ),
    ]
