# Generated by Django 3.1.1 on 2020-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerlerimiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermodel',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='partnermodel',
            name='tweetter',
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='alan',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Çalışma Alanı Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Facebook Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='İnstagram Ekleyin'),
        ),
    ]
