# Generated by Django 3.1.1 on 2020-09-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerlerimiz', '0002_auto_20200919_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='facebook',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Facebook Linki Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='instagram',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='İnstagram Linki Ekleyin'),
        ),
    ]
