# Generated by Django 3.1.1 on 2020-09-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerlerimiz', '0004_auto_20200928_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='contextslogan',
            field=models.CharField(max_length=100, null=True, verbose_name='Açıklama Slogan Ekleyin'),
        ),
    ]
