# Generated by Django 3.1.1 on 2020-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerlerimiz', '0005_auto_20200928_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='alan',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Çalışma Alanı Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='contextSubtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Açıklama Alt Başlık Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='contextparagraf',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Açıklama Paragrafı  Ekleyin'),
        ),
        migrations.AlterField(
            model_name='partnermodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='İsim Ekleyin'),
        ),
    ]
