# Generated by Django 3.1.1 on 2020-10-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerlerimiz', '0006_auto_20200928_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnermodel',
            name='contextslogan',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Açıklama Slogan Ekleyin'),
        ),
    ]
